/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CampsRouteImport } from './routes/camps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'

const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/impact': typeof ImpactRoute
  '/journal': typeof JournalRoute
  '/journeys': typeof JourneysRoute
  '/regions': typeof RegionsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/impact': typeof ImpactRoute
  '/journal': typeof JournalRoute
  '/journeys': typeof JourneysRoute
  '/regions': typeof RegionsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camps': typeof CampsRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/experiences': typeof ExperiencesRoute
  '/impact': typeof ImpactRoute
  '/journal': typeof JournalRoute
  '/journeys': typeof JourneysRoute
  '/regions': typeof RegionsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camps'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/impact'
    | '/journal'
    | '/journeys'
    | '/regions'
    | '/destinations/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camps'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/impact'
    | '/journal'
    | '/journeys'
    | '/regions'
    | '/destinations/$slug'
  id:
    | '__root__'
    | '/'
    | '/camps'
    | '/contact'
    | '/destinations'
    | '/experiences'
    | '/impact'
    | '/journal'
    | '/journeys'
    | '/regions'
    | '/destinations/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampsRoute: typeof CampsRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  ExperiencesRoute: typeof ExperiencesRoute
  ImpactRoute: typeof ImpactRoute
  JournalRoute: typeof JournalRoute
  JourneysRoute: typeof JourneysRoute
  RegionsRoute: typeof RegionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps': {
      id: '/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
  }
}

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampsRoute: CampsRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  ExperiencesRoute: ExperiencesRoute,
  ImpactRoute: ImpactRoute,
  JournalRoute: JournalRoute,
  JourneysRoute: JourneysRoute,
  RegionsRoute: RegionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
